name: Publish Package to npmjs
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'bump version')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm run install
      - run: npm run build:tailwind-prod
      - run: npm run compile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
